### ISSUE TITLE
Out of memory 

### ISSUE THREAD

**Issue by pdoggyster** [allure-framework/allure-teamcity-plugin#25]
We use this plugin in the TeamCity and it was worked well but since we started using it more building we get the java.lang.OutOfMemoryError: PermGen space exception. We increased the Permsize to 512m in the TC agent but it didn't solved the problem. 
Is it possible that the plugin leaks?
```
ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.reflect.InvocationTargetException
	at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:135)
	at ru.yandex.qatools.allure.teamcity.AgentBuildEventsProvider.runnerFinished(AgentBuildEventsProvider.java:79)
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:121)
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:71)
	at com.sun.proxy.$Proxy9.runnerFinished(Unknown Source)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.finish.FireRunnerFinishedFStage.doFinishStage(FireRunnerFinishedFStage.java:29)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerFinishStagesExecutor.runFinishStage(RunnerFinishStagesExecutor.java:32)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerFinishStagesExecutor.doBuildFinishStages(RunnerFinishStagesExecutor.java:23)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.safeCallFinishStages(RunnerContextExecutor.java:65)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:56)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70)
	at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:265)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:52)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:231)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:132)
	... 28 more
Caused by: java.lang.OutOfMemoryError: PermGen space
```

**Comment by sergmal** [comment]
Hi, I had similar issue today! 
For me helped increasing agent memory.

SET TEAMCITY_AGENT_MEM_OPTS_ACTUAL=-Xmx1100m -XX:MaxPermSize=120m

**Comment by pdoggyster** [comment]
We tried these:
first test: 
 - SET TEAMCITY_AGENT_MEM_OPTS_ACTUAL=-Xmx512m -XX:MaxPermSize=512m
second test: 
- SET TEAMCITY_AGENT_MEM_OPTS_ACTUAL=-Xmx512m -XX:MaxPermSize=1024m

But these didn't help.  :(

**Comment by baev** [comment]
Summon @eroshenkoam

**Comment by pdoggyster** [comment]
FYI: I set the allure report version 1.4.0 in the Team City plugin then it works well but I set back to 1.4.14 then I get the exception again.

**Comment by baev** [comment]
@pdoggyster could you please specify the size of your allure-results folder and count of `testsuite.xml` files?

**Comment by pdoggyster** [comment]
file size: 92 713byte 
file count: 1

But now we try to increase the xmx parameter.

**Comment by baev** [comment]
@pdoggyster hm...weird

could you send me the `allure-results` folder (charlie at yandex-team.ru)?

**Comment by pdoggyster** [comment]
I created 3 empty build step in TC, but the allure reporter build feature was turn on and the out of memory already came. So the test suite XML is not important.

**Comment by baev** [comment]
@pdoggyster I spend some time to investigate the problem:

### Version 1.4.0 PermGen usage
![2015-06-29 15 50 49](https://cloud.githubusercontent.com/assets/2149631/8408241/07f51be8-1e77-11e5-9d06-15eb47f7261d.png)

### Version 1.4.14 PermGen usage
![2015-06-29 15 52 11](https://cloud.githubusercontent.com/assets/2149631/8408250/148ff508-1e77-11e5-81f9-81c1409d84a3.png)

As you can see there is no big difference in memory usage.

Also all works fine with TeamCity (I configure 64m of PremGen, mac agent, teamcity 9.0.2 running via https://github.com/nskvortsov/teamcity-sdk-maven-plugin).

**Comment by pdoggyster** [comment]
Thanks for the information. Try to run this build setup 3 or 4 times. If it is reaching the PermGen limit then the Allure 1.4.14 version will freeze but the 1.4.0 will empty the permgen memory and can run on.

**Comment by baev** [comment]
@pdoggyster I found the problem (bug in guice 3.0, fixed since 4.0). New version of allure should fix this issue

**Comment by pdoggyster** [comment]
This is a good news! I'm looking forward to the new version.

**Comment by baev** [comment]
@pdoggyster it turned out that there is also problems with groovy (see https://issues.apache.org/jira/browse/GROOVY-7484). So I propose the following solution:

* Update Guice version in allure-report-data (https://github.com/allure-framework/allure-core/pull/620)
* Release new report builder with excluded `sisu-guice` dependency (god damn they just copy some classes from guice 3.0, so it affects the report generation too) 
* Release new version of teamcity plugin and use https://confluence.jetbrains.com/display/TCD9/Build+Runner+Plugin to run report generation beyond the agent JVM. 

This steps helps us to avoid OOM for now. In general we should wait while issue https://issues.apache.org/jira/browse/GROOVY-7484 will be solved and then release new version of allure with new version of groovy

**Comment by pdoggyster** [comment]
The GROOVY-7484 solved. Is it solved this bug? When will you release?

**Comment by baev** [comment]
@pdoggyster we are working on this

**Comment by pdoggyster** [comment]
Okay, Thanks for the efforts!

**Comment by baev** [comment]
@pdoggyster for now you can try to use the beta version of new plugin https://github.com/allure-framework/allure-teamcity-plugin/releases/tag/2.1-beta

**Comment by pdoggyster** [comment]
We will check it. I will inform you about the result.

**Comment by pdoggyster** [comment]
I found a bug: the allure result directory value is restored to the default value.
Steps: 1. I modified this value
2. Save it
3. Edit
The result: The value is restored to the default value

**Comment by baev** [comment]
@pdoggyster yep, I see. Thanks

**Comment by pdoggyster** [comment]
We finished the plugin of memory leak issue tests. It looks good, the memory usage normal, no leak.
We are waiting for the final release!

**Comment by baev** [comment]
fixed via https://github.com/allure-framework/allure-teamcity-plugin/pull/28 . The release and documentation is coming soon.

**Comment by baev** [comment]
@pdoggyster https://github.com/allure-framework/allure-teamcity-plugin/releases/tag/allure-teamcity-plugin-2.1
